function [] = displayGasParameters(inputArg1)
%DISPLAYGASPARAMETERS Summary of this function goes here
%   Detailed explanation goes here
gasPressures = inputArg1;
% outputArg2 = inputArg2;

%  Auto-generated by MATLAB on 03-Feb-2020 12:11:45

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
names=fieldnames(gasPressures);
disp(names);
for i = 1:length(names)
   plot(gasPressures.(names{i}));
   hold on;
end
hold off

% Create ylabel
ylabel('Gas Pressures');

% Create xlabel
xlabel('Time (seconds)');

% Create title
title('Gas Pressure Over Time');

names_updated = [];
for n = 1:length(names)
    names_updated = [names_updated; strrep(names{n}, "_", "")];
end
legend(names_updated, 'location', "southwest")

box(axes1,'on');

end

